
language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coveralls
script:
  # - coverage run --source=lol setup.py
  - python -m pytest ./lol/tests/tests.py
after_success:
  - coveralls